### ISSUE TITLE
Use median instead of mean

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [phu54321/anki_plugins#16]
Hi,
I use this addon a lot for work and was interested in your opinion on this.
The median is not really impacted by extreme values so I think it would be wiser to use the median instead of the mean to make the estimate.

This would also fix #12 because stepping outside the deck will add an extreme value.

A compromise would be to use the average of the mean and the median but whatever.

**Comment by phu54321** [comment]
Sorry for late reply :(

I think the mean should be more representative instead of the median. In my experience, a small fraction of my cards is the thing that drags my study schedule. Like 20-80 rule, you know, 20% of cards takes 80% of cards to review.

I think it's okay to strip top & bottom 3% of extremities from statistics, but little skeptical about that idea again.

**Comment by thiswillbeyourgithub** [comment]
Thanks for answering.

Interesting idea but 3% seems a bit random to me, what do you think of averaging the mean and the median?

**Comment by phu54321** [comment]
That seems rather artificial.
