### ISSUE TITLE
Additional feature 

### ISSUE THREAD

**Issue by fem57** [phu54321/anki_plugins#9]
Is there anyway we could make it so when you leave a deck the timer resets? The old one did this. Because sometimes i get bored of a deck and I want to do another deck. When i go back into the other deck the timer still is going and it says like 600 minutes till completion.

**Comment by phu54321** [comment]
The code structure has changed significantly between 2.0 version and 2.1 version of remaining time addon. It would take a while to port back good old behaviors. Stay tuned :)

**Comment by thiswillbeyourgithub** [comment]
Hi,
I wanted to add that it would be great if the addon didn't take into account the amount of time to answer that are longer than the "ignore answer times longer than X sec" in the settings.

Also, maybe indicating the median interval instead of the mean, or the average of the two would make it more robust to extreme values

**Comment by phu54321** [comment]
Closed as of 510a5bde4b605a31112d8a479487ecc4176ee9c6
